version: "3"
services:
  hello-boomer:
    build: MonApplication
    ports:
      - "8080:3000"
  db:
    image: postgres:9.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: boomer
